=== Alek7eeey/Semestr_4_POIT/internet_programming_technology/Lab's/Lab_4/Lab_4/Files/xmlFile.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns="http://msiter.ru"
           targetNamespace="http://msiter.ru"
           elementFormDefault="qualified"
           attributeFormDefault="unqualified">

  <xs:element name="employees">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="employee" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="name" type="xs:string"/>
              <xs:element name="higherEducation" type="xs:boolean"/>
              <xs:element name="position" type="xs:string"/>
              <xs:element name="salary" type="xs:integer"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== Alek7eeey/Semestr_4_POIT/internet_programming_technology/Lab's/Lab_4/Lab_4/Files/xmlFile.xml
<?xml version="1.0" encoding="UTF-8"?>

<employees xsi:schemaLocation="http://msiter.ru xmlFile.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://msiter.ru">
  <employee>
    <name>John Doe</name>
    <higherEducation>true</higherEducation>
    <position>senior</position>
    <salary>100000</salary>
  </employee>
  <employee>
    <name>Jane Smith</name>
    <higherEducation>false</higherEducation>
    <position>junior</position>
    <salary>50000</salary>
  </employee>
  <employee>
    <name>Bob Johnson</name>
    <higherEducation>true</higherEducation>
    <position>middle</position>
    <salary>75000</salary>
  </employee>
</employees>
